# Generated by Django 5.1 on 2024-08-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_curiosidades_gostospessoais_delete_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobreMim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='sobre_mim/')),
            ],
        ),
    ]
